name: Publish

on:
 workflow_dispatch:
 push:
  branches:
  - master
  
env: 
 AZURE_WEBAPP_NAME: nunit-api
 AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  
jobs:
 publish: 
  runs-on: ubuntu-lastes

  steps:
   - uses: actions/checkout@v3
   
   - name: Setup .NET
     uses: actions/sertup-dotnet@v3
     with: 
        dotnet-version: '7.0.x'
      
   - name: Restore
     run: dotnet restore ./Nunit.Api.sln
     
   - name: Build
     run: dotnet build ./Nunit.Api.sln --configuration Release --no-restore
       
   - name: Publish
     run: dotnet build ./Nunit.Api.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
     
   - name: Deployment
     uses: actions/webapps-deply@2
     with:
      app-name: ${{ AZURE_WEBAPP_NAME }}
      publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
      package: ${{ AZURE_WEBAPP_PACKAGE_PATH }}
      
